spring:
  application:
    name: binderBack
  datasource:
    url: jdbc:postgresql://81.94.156.182:7777/tinder-book
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger/src
  api-docs:
    path: /swagger/docs
token:
  signing:
    key: ADN24192ujfa9hf0h308thgf9238fgp9wajfpw3hrfp983hrfwp3hfpw3hfphwfhseo
